language: python
python:
  - 2.7
  - 3.5
install:
  - pip install -r requirements.txt
  - pip install -e .

script:
  - py.test -v
  - ./nsisdump.py tests/samples/example1.exe

addons:
  apt_packages:
    - swig
